# pipeline for dotnet-core-helloWorld app.

groups:
- name: dotnet-resource-test-library
  jobs:
  - build-service

resource_types:
- name: dotnet
  type: docker-image
  source:
    repository: 172.20.11.149:5000/dotnet-resource
    tag: "latest"
    insecure_registries: [ "172.20.11.149:5000" ]

resources:
- name: library-repo
  type: git
  source:
    uri: https://github.com/miclip/dotnet-resource-test-library.git
    branch: master    

- name: dotnet-build
  type: dotnet 
  source:
    framework: netcoreapp2.1
    runtime: ubuntu.14.04-x64
    nuget_source: https://www.myget.org/F/dotnet-resource-test/api/v3/index.json
    nuget_apikey: 
  
jobs:
- name: build-service
  public: true
  serial: true
  plan:
  - get: library-repo
    trigger: true
  - put: dotnet-build    
    params:
     project: library-repo/DotnetResource.sln
     testfilter: "*.Tests.csproj"
     version: "1.0.*"
     
    
  